---
# This Playbook will deploy the whole Spark + Hive + HDFF on the cluster

#- hosts: all
#  remote_user: ubuntu 
#  roles:
#  - common

- hosts: master
  remote_user: ubuntu 
  roles:
    - role: master

