# vim:ft=ansible:
---
# This Playbook is used to deploy Spark, Hive and HDFS worker node

- name: Create directory /mnt/u1 for HDFS name node
  file: path=/mnt/u1/hadoop/data state=directory mode=0755 owner=ubuntu
  become: yes

- name: Create directory /mnt/u2 for HDFS name node
  file: path=/mnt/u2/hadoop/data state=directory mode=0755 owner=ubuntu
  become: yes

- include: sync.yml
