# vim:ft=ansible:
---
# This Playbook is used to deploy Spark, Hive and HDFS worker node

#- name: Sync Spark source code and configuration from the master
#  synchronize:
#    src: '/home/ubuntu/spark-1.6.1'
#    dest: /home/ubuntu/
#    rsync_opts:
#      - "--exclude=.git"
#      - "--exclude=logs"
#  delegate_to: "{{ groups.master[0] }}"
  #with_items:
  #  - 'spark-1.6.1'
  #  - 'hadoop-2.6.4'
  #  - 'hive-1.2.1'

- name: Sync configurations and source code
  command: 'rsync -az --exclude logs --exclude .git {{ groups.master[0] }}:/home/ubuntu/{{ item }} /home/ubuntu'
  with_items:
    - 'spark-1.6.1'
    - 'hadoop-2.6.4'
    - 'hive-1.2.1'

#- name: Sync HDFS source code and configuration from the master
#  synchronize:
#    src: '/home/ubuntu/hadoop-2.6.4'
#    dest: /home/ubuntu/
#    rsync_opts:
#      - "--exclude=.git"
#      - "--exclude=logs"
#  delegate_to: "{{ groups.master[0] }}"

#- name: Sync Hive source code and configuration from the master
#  synchronize:
#    src: '/home/ubuntu/hive-1.2.1'
#    dest: /home/ubuntu/
#    rsync_opts:
#      - "--exclude=.git"
#      - "--exclude=logs"
#  delegate_to: "{{ groups.master[0] }}"

- name: Spark master variable
  set_fact: master='{{ groups.master[0] }}'

- name: Spark worker public_dns variable
  set_fact: public_dns='{{ inventory_hostname }}'

- name: Update Spark configuration spark-env.sh per worker
  template: src='{{ inventory_dir }}/roles/master/templates/spark/spark-env.j2' dest=/home/ubuntu/spark-1.6.1/conf/spark-env.sh
