# vim:ft=ansible:
---
# This Playbook is used for instance flavor m3.x2large to mount 2xSSD

- name: Create directory HDFS name node
  file: path=/mnt/hadoop/name state=directory mode=0755 owner=ubuntu
  become: yes

- name: Create directory for HDFS name node
  file: path=/mnt/hadoop/data state=directory mode=0755 owner=ubuntu
  become: yes

- name: Create directory for HDFS name node
  file: path=/mnt/hadoop/data state=directory mode=0755 owner=ubuntu
  become: yes
