# vim:ft=ansible:
---
# This Playbook runs all the common plays in the deployment

- name: Init locale for new instance
  apt: name=language-pack-en

- name: Install git
  apt: name=git

- name: Create the Downloads directory for all machines
  file: path=/home/ubuntu/Downloads state=directory mode=0755 owner=ubuntu

- name: Install Oracle Java 8 install python-software-properties
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Setup JAVA_HOME
  lineinfile: dest=/home/ubuntu/.bashrc line="export JAVA_HOME=/usr/lib/jvm/java-8-oracle/"

- name: Setup PATH
  lineinfile: dest=/home/ubuntu/.bashrc line="PATH=$PATH:/usr/lib/jvm/java-8-oracle/jre/bin/"

- name: Install iostate
  apt: name=sysstat state=latest

- name: Create a directory for JvmTop
  file: path=/home/ubuntu/jvmtop state=directory mode=0755 owner=ubuntu

- name: Download JvmTop
  get_url: url=https://github.com/patric-r/jvmtop/releases/download/0.8.0/jvmtop-0.8.0.tar.gz dest=/home/ubuntu/Downloads

- name: Extract JvmTop
  unarchive: src=/home/ubuntu/Downloads/jvmtop-0.8.0.tar.gz dest=/home/ubuntu/jvmtop/

- name: Make JvmTop executable
  command: chmod +x /home/ubuntu/jvmtop/jvmtop.sh

- name: Install dependencies for nethogs
  apt: name={{ item }}
  with_items:
    - build-essential
    - libncurses5-dev
    - libpcap-dev

- name: Git clone nethogs source code
  git: repo=https://github.com/raboof/nethogs dest=/home/ubuntu/Downloads/nethogs

- name: Compile nethogs
  make: chdir=/home/ubuntu/Downloads/nethogs target=install
  become: yes

- name: Reboot all instances
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: Waiting for all instances to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  sudo: false
