# vim:ft=ansible:
---
# This Playbook runs all the common plays in the deployment

- name: Install toolchain
  include: install_toolchain.yml
  
- name: SSH configuration
  include: ssh_config.yml

- name: Setup env variables
  include: setup_env.yml

- name: EBS volumes
  include: ebs_mount.yml init='yes'

- name: Reboot all instances
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: yes
  ignore_errors: true

- name: Waiting for all instances to come back
  local_action: wait_for port=22 host={{ inventory_hostname }} state=started
