# vim:fs=ansible:
---
# This Playbook will

- name: Update configuration for Spark
  include: roles/master/tasks/config/config_spark.yml

- name: Update configuration for HDFS
  include: roles/master/tasks/config/config_hdfs.yml

- name: Update configuration for Hive
  include: roles/master/tasks/config/config_hive.yml

- name: Sync to all worker nodes
  include: roles/master/tasks/sync.yml

