---
# This Playbook builds Spark, HDFS and Hive on Master Node

- name: Copy Spark, HDFS and Hive code base to Master Node
  copy: src=spark_hdfs_hive.tar.gz dest=/home/ubuntu/Downloads 

- name: Extract code bases to HOME
  unarchive: src=/home/ubuntu/Downloads/spark_hdfs_hive.tar.gz dest=/home/ubuntu/

- name: Update configuration file
  

- name: Launch HDFS, Spark
  command: chdir={{ item.dir }} {{ item.cmd }}
  with_items:
    - { dir: '', cmd: '' }
    - { dir: '', cmd: '' }
    - { dir: '', cmd: '' }
