---
# This Playbook builds Spark, HDFS and Hive on Master Node

- name: Copy Spark, HDFS and Hive code base to Master Node
  copy: src=spark_hdfs_hive.tar.gz dest=~/Downloads 

- name: Extract code bases to HOME
  command: tar -xf ~/Downloads/spark_hdfs_hive.tar.gz -C ~/

- name: Update configuration file
  

- name: Launch HDFS, Spark
  command: chdir={{ item.dir }} {{ item.cmd }}
  with_items:
    - { dir: '', cmd: '' }
    - { dir: '', cmd: '' }
    - { dir: '', cmd: '' }
