# vim:ft=ansible:
---
# This Playbook updates configuration for HDFS

- name: HDFS namenode variable
  set_fact: master='{{ groups.master[0] }}'

- name: HDFS datanodes variable
  set_fact: worker_list='{{ groups.worker }}'

- name: Obtain AWS_ACCESS_KEY_ID from local env var
  set_fact: aws_access_key_id="{{ lookup('file', '~/.AWS_ACCESS_KEY_ID') }}"

- name: Obtain AWS_SECRET_ACCESS_KEY from local env var
  set_fact: aws_secret_key="{{ lookup('file', '~/.AWS_SECRET_ACCESS_KEY') }}"

- name: Update core-site.xml 
  template: src='{{ inventory_dir }}/roles/master/templates/hadoop/core-site.j2' dest=/home/ubuntu/hadoop-2.6.4/etc/hadoop/core-site.xml

- name: Update hdfs-site.xml
  template: src='{{ inventory_dir }}/roles/master/templates/hadoop/hdfs-site.xml' dest=/home/ubuntu/hadoop-2.6.4/etc/hadoop/hdfs-site.xml

- name: Update slaves
  template: src='{{ inventory_dir }}/roles/master/templates/hadoop/slaves.j2' dest=/home/ubuntu/hadoop-2.6.4/etc/hadoop/slaves

