# vim:ft=ansible:
---
# This playbook is used to launch multiple EC2 instances in all regions

- hosts: localhost
  vars:
    keypair: hao-savi-rsa
    security_group: hao
    #    instance_type: m3.2xlarge
    instance_type: t2.micro
    vm_num: 2


  tasks:
    - name: Launch a master instance
      ec2:
        keypair: "{{ keypair }}"
        region: 'us-east-1'
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        instance_tags:
          Name: master-hao
        image: 'ami-fce3c696'
        count: 1
        wait: no
      register: ec2

    - name: Launch worker instances
      ec2: 
        keypair: "{{ keypair }}"
        region: "{{ item.region }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        instance_tags:
          Name: worker-hao
        image: "{{ item.image }}"
        count: "{{ vm_num }}"
        wait: no
      with_items:
        - { region: 'us-east-1', image: 'ami-fce3c696'}
        - { region: 'us-west-1', image: 'ami-06116566'}
        - { region: 'us-west-2', image: 'ami-9abea4fb'}
        - { region: 'eu-west-1', image: 'ami-f95ef58a'}
        - { region: 'eu-central-1', image: 'ami-87564feb'}
        - { region: 'ap-northeast-1', image: 'ami-a21529cc'}
        - { region: 'ap-northeast-2', image: 'ami-09dc1267'}
        - { region: 'ap-southeast-1', image: 'ami-25c00c46'}
        - { region: 'ap-southeast-2', image: 'ami-6c14310f'}
        - { region: 'sa-east-1', image: 'ami-0fb83963'}
      register: ec2


