# vim:ft=ansible
---
# This Playbook will setup security group to all regions of EC2

- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Create the security group for all regions
    local_action:
      module: ec2_group
      name: '{{ security_group}}'
      description: "ansible generated group"
      region: "{{ item }}"
      rules:
        - proto: all
          cidr_ip: "0.0.0.0/0"
      rules_egress:
        - proto: all
          cidr_ip: "0.0.0.0/0"
    with_items:
      - us-east-1
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-central-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - sa-east-1
