# vim:ft=ansible:
---
# This Playbook will be called by ec_admin.yml.
# Regenerate the hosts file after instances are restarted

- name: Collect instance information
  ec2_remote_facts:
    region: '{{ item.region }}'
    filters:
      instance.group-name: '{{ security_group }}'
  with_items:
    - '{{ regions }}'
  register: ec2_info

- name: Parsing ec2_info
  set_fact: instance_list={{ ec2_info.results | map(attribute='instances') | list }}

- name: setup master
  set_fact: master="{% for instances in instance_list %}{% for instance in instances %}{% if instance.tags.Name == 'master-hao' %}{{ instance }}{% endif %}{% endfor %}{% endfor %}"

- name: setup master
  set_fact: worker_list='{{ instance_list }}'

- name: Generate inventory file hosts
  template: src='{{ inventory_dir }}/templates/hosts.j2' dest='{{ inventory_dir }}/hosts'
