# vim:ft=ansible:
---
# This playbook is used to launch multiple EC2 instances in all regions

- hosts: localhost
  vars:
    keypair: hao-savi-rsa
    security_group: hao
    # instance_type: m3.2xlarge
    instance_type: t2.micro
    vm_num: '{{ num }}'

  tasks:
    - name: Include regions variable
      include_vars: '{{ inventory_dir }}/group_vars/regions.yml'
        
    - name: Launch a master instance
      ec2:
        keypair: '{{ keypair }}'
        region: 'us-east-1'
        group: '{{ security_group }}'
        instance_type: '{{ instance_type }}'
        instance_tags:
          Name: master-hao
          image: 'ami-fce3c696'
          count: 1
          wait: yes
      register: ec2_master

    - name: Save ec2_master public ip to inventory
      set_fact: master='{{ item }}'
      with_flattened:
        - '{{ ec2_master.instances }}'

    - name: Launch worker instances
      ec2: 
        keypair: '{{ keypair }}'
        region: '{{ item.region }}'
        group: '{{ security_group }}'
        instance_type: '{{ instance_type }}'
        instance_tags:
           Name: worker-hao
        image: '{{ item.image }}'
        count: '{{ vm_num }}'
        wait: yes
      with_items:
        - '{{ regions }}'
      register: ec2_worker

    - name: Flattening worker_list
      set_fact: > 
        worker_list="{{ ec2_worker.results | map(attribute='instances') | list }}"

    #- debug: msg='{{ master.public_ip }}'

    #- debug: msg='{{ worker_list }}'

    - name: Generate inventory file hosts
      template: src='{{ inventory_dir }}/templates/hosts.j2' dest='{{ inventory_dir }}/hosts'
