# vim:ft=ansible:
---
# This playbook is deprecated.
# Using "ec2_admin.yml -e action=stopped" instead.

- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Stop master
      local_action:
        module: ec2
        instance_tags:
          Name: master-hao
        region: 'us-east-1'
        state: 'stopped'

    - name: Stop all workers in all regisons
      local_action:
        module: ec2
        instance_tags:
          Name: worker-hao
        region: '{{ item }}'
        state: 'stopped'
      with_items:        
        - 'us-east-1'
        - 'us-west-1'
        - 'us-west-2'
        - 'eu-west-1'
        - 'eu-central-1'
        - 'ap-northeast-1'
        - 'ap-northeast-2'
        - 'ap-southeast-1'
        - 'ap-southeast-2'
        - 'sa-east-1'

