# vim:ft=ansible:
---
# This Playbook will walk through instances in all regions and operate on them

- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Collect instance information
      ec2_remote_facts:
        region: '{{ item }}'
        filters:
          instance.group-name: 'hao'
      with_items:
        - 'us-east-1'
        - 'us-west-1'
        - 'us-west-2'
        - 'eu-west-1'
        - 'eu-central-1'
        - 'ap-northeast-1'
        - 'ap-northeast-2'
        - 'ap-southeast-1'
        - 'ap-southeast-2'
        - 'sa-east-1'
      register: ec2_info

    - name: Parsing ec2_info
      set_fact: instance_list={{ ec2_info.results | map(attribute='instances') | list }}
   
    - name: Execute EC2 admin operation to all instances
      local_action:
        module: ec2
        instance_ids: '{{ item.id }}'
        region: '{{ item.region }}'
        state: '{{ action }}'
        wait: yes
      with_flattened:
        - '{{ instance_list }}'

    - name: Re-generate inventory file hosts after restart
      include: ec2_restore.yml
      when: action =='running'
