# vim:ft=ansible:
---
# This playbook is used to launch multiple EC2 instances in all regions

- hosts: localhost
  tasks:
    - name: Include regions variable
      include_vars: '{{ inventory_dir }}/group_vars/regions.yml'
        
    - name: Launch a master instance
      ec2:
        keypair: '{{ keypair }}'
        region: 'us-east-1'
        group: '{{ security_group }}'
        instance_type: '{{ instance_type }}'
        instance_tags:
          Name: '{{ master_name }}'
        image: 'ami-fce3c696'
        volumes:
          - device_name: '{{ device_name }}'
            volume_type: '{{ volume_type }}'
            volume_size: '{{ volume_size }}'
            delete_on_termination: '{{ delete_on_termination }}'
        count: 1
        wait: yes
      register: ec2_master

    - name: Save ec2_master public ip to inventory
      set_fact: master='{{ item }}'
      with_flattened:
        - '{{ ec2_master.instances }}'

    - name: Launch worker instances
      ec2: 
        keypair: '{{ keypair }}'
        region: '{{ item.region }}'
        group: '{{ security_group }}'
        instance_type: '{{ instance_type }}'
        instance_tags:
          Name: '{{ worker_name }}'
        image: '{{ item.image }}'
        volumes:
          - device_name: '{{ device_name }}'
            volume_type: '{{ volume_type }}'
            volume_size: '{{ volume_size }}'
            delete_on_termination: '{{ delete_on_termination }}'
        count: '{{ vm_num }}'
        wait: yes
      with_items:
        - '{{ regions }}'
      register: ec2_worker

    - name: Flattening worker_list
      set_fact: > 
        worker_list="{{ ec2_worker.results | map(attribute='instances') | list }}"

    #- debug: msg='{{ master.public_ip }}'

    #- debug: msg='{{ worker_list }}'

    - name: Generate inventory file hosts
      template: src='{{ inventory_dir }}/templates/hosts.j2' dest='{{ inventory_dir }}/hosts'
